### ISSUE TITLE
Running activate.sh fails as submodules are configured to use SSH instead of HTTPS

### ISSUE THREAD

**Issue by sriharshamadala** [microsoft/verismo#7]
Here is a snippet of the failure:
```bash
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ziqiaozhou/verus.git' into submodule path '/home/tadatmya/projects/verismo/tools/verus' failed
Failed to clone 'tools/verus'. Retry scheduled
Cloning into '/home/tadatmya/projects/verismo/tools/verus'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

The fix would be to update the HTTPS URL instead of the SSH. But I noticed that your fork of Verus has diverged from the official one. Which one should I choose?

**Comment by ziqiaozhou** [comment]
Verus official repository is still under active development and its features and syntax are not always consistent. I suggest using my repo to avoid build issues. My verus fork should be relatively new enough. If you want to use latest verus. You can try to apply my change to the latest one.
